pipeline:
    build:
        image: golang
        commands:
            - go get
            - go build
            - go test
services:
    postgres:
        image: postgres:latest
        environment:
        - POSTGRES_USER=ilyaz

